In [1]:
pip install numpy


     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
      --------------------------------------- 0.2/12.9 MB ? eta -:--:--
     - -------------------------------------- 0.4/12.9 MB 3.5 MB/s eta 0:00:04
     - -------------------------------------- 0.6/12.9 MB 3.8 MB/s eta 0:00:04
     --- ------------------------------------ 1.0/12.9 MB 4.7 MB/s eta 0:00:03
     ---- ----------------------------------- 1.5/12.9 MB 5.8 MB/s eta 0:00:02
     ----- ---------------------------------- 1.6/12.9 MB 5.8 MB/s eta 0:00:02
     ------- -------------------------------- 2.3/12.9 MB 6.3 MB/s eta 0:00:02
     --------- ------------------------------ 3.0/12.9 MB 7.3 MB/s eta 0:00:02
     ---------- ----------------------------- 3.3/12.9 MB 7.8 MB/s eta 0:00:02
     ----------- ---------------------------- 3.6/12.9 MB 7.8 MB/s eta 0:00:02
     ------------ --------------------------- 4.0/12.9 MB 7.1 MB/s eta 0:00:02
     ------------ --------------------------- 4.2/12.9 MB 7.0 MB/


[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
b=np.array([1,2,3,4,"5"])

In [6]:
b

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [7]:
type(b)

numpy.ndarray

In [8]:
b.dtype

dtype('<U21')

In [9]:
a.dtype

dtype('int64')

In [10]:
a.shape

(5,)

In [11]:
a.ndim

1

In [12]:
a.itemsize

8

In [13]:
a.nbytes

40

In [14]:
a.size

5

NameError: name 'np' is not defined

In [2]:
a

NameError: name 'a' is not defined

In [5]:
a=np.zeros((2,3))

In [6]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
b=np.ones((3,2)),int

In [15]:
b

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 int)

In [9]:
c=np.eye((3,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [16]:
d=np.ones((2,3)),int

In [17]:
d

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 int)

In [23]:
e=np.eye((5))

In [24]:
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
f=np.eye(5,k=2)

In [30]:
f

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
f=np.eye(5,k=-2)

In [32]:
f

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [36]:
n=np.identity(5)

In [34]:
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
h=np.empty((5,3))

In [3]:
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
d=np.arange(1,100,5)

In [7]:
d

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [12]:
d=np.linspace(1,100,8)

In [13]:
d

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

In [14]:
d=np.linspace(1,100,8,endpoint=True)

In [15]:
d

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

In [16]:
d=np.linspace(1,100,8,endpoint=False)

In [ ]:
d

array([ 1.   , 13.375, 25.75 , 38.125, 50.5  , 62.875, 75.25 , 87.625])

In [3]:
r=np.random.rand(2,3)

In [4]:
r

array([[0.26741725, 0.06554917, 0.6089479 ],
       [0.7315723 , 0.02622732, 0.31779052]])

In [6]:
r=np.random.randint(5,95,(5,3))

In [7]:
r

array([[46, 41, 58],
       [42, 36, 31],
       [10, 31, 60],
       [74, 49, 73],
       [82, 11, 11]], dtype=int32)

In [8]:
r=np.random.choice(5,95(5,3))

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\intel\AppData\Local\Temp\ipykernel_16192\2501116058.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  r=np.random.choice(5,95(5,3))
C:\Users\intel\AppData\Local\Temp\ipykernel_16192\2501116058.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  r=np.random.choice(5,95(5,3))
C:\Users\intel\AppData\Local\Temp\ipykernel_16192\2501116058.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  r=np.random.choice(5,95(5,3))
C:\Users\intel\AppData\Local\Temp\ipykernel_16192\2501116058.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  r=np.random.choice(5,95(5,3))


TypeError: 'int' object is not callable

In [9]:
a=np.array([2,3,4,5,5,6,7,8])
r=np.random.choice(a,(5,3))

In [10]:
r

array([[5, 3, 8],
       [7, 5, 5],
       [2, 3, 2],
       [3, 5, 4],
       [2, 2, 7]])

In [ ]:
# success hum jada chahte hai failer kam iske liye
#  probalty use krte hai p name ke variable se
a=np.array(["success","failer"])
r=np.random.choice(a,(5,2),p=[0.7,0.3])

In [12]:
r

array([['success', 'failer'],
       ['failer', 'failer'],
       ['success', 'success'],
       ['failer', 'success'],
       ['success', 'success']], dtype='<U7')

In [17]:
a=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# np.enumerater me index pe kaun value hai o btayga 
a=np.array([[1,2,3],[4,5,6]])
for i,j in np.ndenumerate(a):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [6]:
# flatten
a=np.array([[1,2,3,4]])
b=a.flatten()
b[0]=50

In [2]:
b

NameError: name 'b' is not defined

In [5]:
b

array([1, 2, 3, 4])

In [7]:
b

array([50,  2,  3,  4])

In [8]:
a

array([[1, 2, 3, 4]])

In [11]:
a=np.array([[1,2,3,4]])
b=a.ravel()
b[0]=100


In [10]:
b

array([1, 2, 3, 4])

In [12]:
b

array([100,   2,   3,   4])

In [13]:
a

array([[100,   2,   3,   4]])

In [ ]:
# concanate
a=np.array([[1,2,3],[4,4,5]])
b=np.array([[6,7,8],[5,6,9]])
c=np.concatenate((a,b))

In [16]:
c

array([[1, 2, 3],
       [4, 4, 5],
       [6, 7, 8],
       [5, 6, 9]])

In [18]:
a=np.array([[1,2,3],[4,4,5]])
b=np.array([[6,7,8],[5,6,9]])
c=np.concatenate((a,b),axis=1)

In [19]:
c

array([[1, 2, 3, 6, 7, 8],
       [4, 4, 5, 5, 6, 9]])

In [ ]:
# spilit
a=np.array([1,2,3,4,5,6])
b=np.split(a,2)

In [21]:
b

[array([1, 2, 3]), array([4, 5, 6])]

In [23]:
c = np.split(a,3)

In [24]:
c

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
# reshape
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)

In [26]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(1,2,3)
b.shape

(1, 2, 3)

In [32]:
b

array([[[1, 2, 3],
        [4, 5, 6]]])

In [29]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,-1)

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(1,2,3)
b.shape

(1, 2, 3)

In [38]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,-1)
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
a=np.array([6,5,3,4,2,1])
np.sort(a)

array([1, 2, 3, 4, 5, 6])

In [41]:
a

array([6, 5, 3, 4, 2, 1])

In [2]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,2],[1,4]])
c=np.dot(a,b)

In [3]:
c

array([[ 7, 10],
       [19, 22]])

In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.cross(a,b)
           

In [5]:
c

array([-3,  6, -3])

In [7]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.cross(a,b)

In [8]:
c

array([[-6, 12, -6],
       [-6, 12, -6]])

In [20]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
np.add(a,5)

array([ 6,  7,  8,  9, 10])

In [4]:
c=np.subtract(a,5)

In [5]:
c

array([-4, -3, -2, -1,  0])

In [6]:
np.multiply(a,5)

array([ 5, 10, 15, 20, 25])

In [7]:
np.divide(a,5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [8]:
np.power(a,5)

array([   1,   32,  243, 1024, 3125])

In [9]:
np.sqrt(a,5)

TypeError: return arrays must be of ArrayType

In [10]:
np.square(a,2)

TypeError: return arrays must be of ArrayType

In [11]:
np.sqrt(a,5)

TypeError: return arrays must be of ArrayType

In [12]:

np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [13]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [14]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [15]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [16]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [17]:
np.abs(a)

array([1, 2, 3, 4, 5])

In [18]:
np.mean(a)

np.float64(3.0)

In [19]:
np.median(a)

np.float64(3.0)

In [21]:
np.mean(a)

np.float64(3.5)

In [22]:
np.median(a)

np.float64(3.5)

In [23]:
np.std(a)

np.float64(1.707825127659933)